use tauri::AppHandle;
use crate::core::script_runner::execute_standalone_install;
use crate::commands::updater::get_backend_dir;

/// Tauri Command: install_mod
/// 
/// Orchestrates a standalone installation by extracting the bundled resources
/// to a temporary directory, preparing the model, and executing the bash script.
#[tauri::command]
pub async fn install_mod(
    app: AppHandle,
    game_dir: String,
    route: String,
    bitness: String,
    gpu_arch: String,
    dll_path: Option<String>,
    bin_path: Option<String>,
    shortcut_key: String,
    neural_startup: Option<bool>,
) -> Result<String, String> {
    crate::core::logger::log_launcher(&app, "INFO", &format!("Operação no jogo: rota={route}, arquitetura={bitness}, GPU={gpu_arch}, diretório={game_dir}"));
    let result = async {
    // Validate the selected model before copying resources or starting the installer.
    if route != "remove" {
        if let Some(ref bin) = bin_path {
            if !std::path::Path::new(bin).is_file() {
                return Err("MODEL_BIN_NOT_FOUND".to_string());
            }
        }
    }
    let base_dir = get_backend_dir(&app)?;
    let resource_path = base_dir.join(&gpu_arch).join(&bitness);

    if !resource_path.exists() {
        return Err("Arquivos do backend não encontrados! Clique no botão de Atualizar no topo direito para baixar os arquivos necessários.".to_string());
    }

    let output = execute_standalone_install(&resource_path, &game_dir, &route, dll_path.as_ref(), bin_path.as_ref(), &shortcut_key)?;
    if route != "remove" {
        if let Some(enabled) = neural_startup {
            super::neural_settings::set_enabled(std::path::Path::new(&game_dir), enabled)?;
        }
    }
    Ok(output)
    }.await;
    super::analyzer::invalidate_game(&app, &game_dir);
    crate::core::logger::log_result(&app, "Instalação/remoção do mod", &result);
    result
}

#[tauri::command]
pub fn check_cached_bin(app: AppHandle, bitness: String, gpu_arch: String) -> Result<Option<String>, String> {
    use std::fs;
    use tauri::Manager;
    
    // Check global bin path generated by extract_dll_wizard
    let base_dir = app.path().config_dir().map_err(|e| e.to_string())?.join("dlssnr-x-amd");
    let global_bin = base_dir.join("dlssnr.bin");
    
    if global_bin.exists() {
        return Ok(Some(global_bin.to_string_lossy().to_string()));
    }

    Ok(None)
}

use crate::core::script_runner::inject_shortcut_key_pub;

#[tauri::command]
pub fn update_shortcut_key_in_game(game_dir: String, shortcut_key: String) -> Result<(), String> {
    inject_shortcut_key_pub(&game_dir, &shortcut_key)
}

use crate::commands::analyzer::scan_directory_for_exe;

#[derive(serde::Serialize)]
pub struct GameInstallationDetails {
    status: String,
    installed_dll: Option<String>,
}

fn details_in_directory(dir: &std::path::Path) -> GameInstallationDetails {
    let has = |names: &[&str]| names.iter().any(|name| dir.join(name).is_file());
    // Proxy DLL names alone are not evidence: games, DXVK and other tools ship them too.
    let optiscaler = has(&["OptiScaler.dll", "OptiScaler.ini", "dlssnr_core.dll", "nvngx.dll_dlssnr.dll", "nvngx_dlssnr.dll"]);
    let addon = has(&["dlssnr_amd.addon64", "dlssnr_amd.addon32"]);
    let manifest = dir.join("dlssnr-amd-install.txt").is_file()
        && dir.join("dlssnr-amd/dlssnr.bin").is_file();
    let proxy_names = ["vulkan-1.dll", "winevulkan.dll", "dxgi.dll", "d3d9.dll", "winmm.dll", "version.dll", "d3d12.dll", "d3d11.dll", "dinput8.dll", "ReShade64.dll", "ReShade32.dll", "OptiScaler.dll"];
    // Prefer the loader recorded by the installer over similarly named original game DLLs.
    use std::io::Read;
    let mut recorded_files = String::new();
    if let Ok(file) = std::fs::File::open(dir.join("dlssnr-amd-install.txt")) {
        let _ = file.take(64 * 1024).read_to_string(&mut recorded_files);
    }
    let proxy = proxy_names.iter().find(|name| dir.join(name).is_file()
        && recorded_files.lines().any(|line| line.trim() == **name))
        .or_else(|| proxy_names.iter().find(|name| dir.join(name).is_file()));
    let status = if proxy.is_none() || !(optiscaler || addon || manifest) {
        "Não Instalado"
    } else if optiscaler {
        "OptiScaler"
    } else if matches!(proxy.copied(), Some("vulkan-1.dll" | "winevulkan.dll")) {
        "Vulkan/DX9"
    } else {
        "ReShade"
    };
    let installed_dll = if status == "Não Instalado" { None } else { proxy.map(|name| (*name).to_string()) };
    GameInstallationDetails { status: status.to_string(), installed_dll }
}

pub(crate) fn installed_mod_directory(base_dir: &std::path::Path) -> Option<std::path::PathBuf> {
    if details_in_directory(base_dir).status != "Não Instalado" { return Some(base_dir.to_path_buf()); }
    let exe = scan_directory_for_exe(base_dir)?;
    let dir = exe.parent()?;
    if details_in_directory(dir).status != "Não Instalado" { Some(dir.to_path_buf()) } else { None }
}

fn installation_details(game_dir: &str) -> GameInstallationDetails {
    let base_dir = std::path::Path::new(game_dir);
    if !base_dir.exists() {
        return GameInstallationDetails { status: "Não Instalado".to_string(), installed_dll: None };
    }
    let root_details = details_in_directory(base_dir);
    // install.sh writes into the selected folder, even when the largest EXE is nested.
    // The manifest/add-on/core files identify that folder without another directory walk.
    let root_has_mod = ["dlssnr-amd-install.txt", "dlssnr_core.dll", "OptiScaler.ini", "dlssnr_amd.addon64", "dlssnr_amd.addon32", "ReShade.ini"].iter().any(|name| base_dir.join(name).is_file());
    if root_has_mod && root_details.status != "Não Instalado" { return root_details; }

    // Retain detection for existing installations next to a nested game executable.
    let exe_path = scan_directory_for_exe(base_dir);
    if let Some(dir) = exe_path.as_ref().and_then(|exe| exe.parent()) {
        if dir != base_dir {
            let nested_details = details_in_directory(dir);
            if nested_details.status != "Não Instalado" { return nested_details; }
        }
    }
    root_details
}

#[tauri::command]
pub async fn get_game_installation_details(game_dir: String) -> Result<GameInstallationDetails, String> {
    tauri::async_runtime::spawn_blocking(move || installation_details(&game_dir))
        .await.map_err(|error| error.to_string())
}

#[tauri::command]
pub async fn check_game_installation(game_dir: String) -> Result<String, String> {
    Ok(get_game_installation_details(game_dir).await?.status)
}

#[tauri::command]
pub async fn get_installed_dll(game_dir: String) -> Result<Option<String>, String> {
    Ok(get_game_installation_details(game_dir).await?.installed_dll)
}

#[tauri::command]
pub fn extract_dll(
    app: AppHandle,
    dll_path: String,
    gpu_arch: String,
    bitness: String,
) -> Result<String, String> {
    use std::fs;
    let base_dir = get_backend_dir(&app)?;
    
    // Default to putting it in the backend folder
    let dest_dir = base_dir.join(&gpu_arch).join(&bitness).join("dlssnr-amd");
    if !dest_dir.exists() {
        fs::create_dir_all(&dest_dir).map_err(|e| e.to_string())?;
    }
    
    let dest_path = dest_dir.join("dlssnr.bin");
    fs::copy(&dll_path, &dest_path).map_err(|e| format!("Failed to copy DLL to bin: {}", e))?;
    
    Ok(dest_path.to_string_lossy().to_string())
}

#[tauri::command]
pub async fn extract_dll_wizard(
    app: AppHandle,
    dll_path: String,
    gpu_arch: String,
) -> Result<String, String> {
    use std::fs;
    use std::env;
    use tauri::Manager;
    use crate::core::script_runner;

    let base_dir = app.path().config_dir().map_err(|e| e.to_string())?.join("dlssnr-x-amd");

    if !base_dir.exists() {
        fs::create_dir_all(&base_dir).map_err(|e| e.to_string())?;
    }

    let dest_path = base_dir.join("dlssnr.bin");

    let app_config_backends = get_backend_dir(&app)?;
    // We'll use 64-bit backend as default for extraction
    let resource_path = app_config_backends.join(&gpu_arch).join("64");

    if !resource_path.exists() {
        return Err("Backend não encontrado! Certifique-se de baixar primeiro.".to_string());
    }

    let temp_game_dir = env::temp_dir().join(format!("dummy-game-{}", uuid::Uuid::new_v4()));
    fs::create_dir_all(&temp_game_dir).map_err(|e| e.to_string())?;

    // Run the heavy I/O work in a blocking thread pool to avoid freezing the UI
    let resource_path_clone = resource_path.clone();
    let temp_game_dir_clone = temp_game_dir.clone();
    let dll_path_clone = dll_path.clone();

    let res = tokio::task::spawn_blocking(move || {
        script_runner::execute_standalone_install(
            &resource_path_clone,
            &temp_game_dir_clone.to_string_lossy(),
            "reshade",
            Some(&dll_path_clone),
            None,
            "Insert",
        )
    }).await.map_err(|e| format!("Task error: {}", e))?;

    let _ = fs::remove_dir_all(&temp_game_dir);

    if res.is_err() {
        return Err(res.unwrap_err());
    }

    // After standalone install, the bin should be cached at resource_path/dlssnr-amd/dlssnr.bin
    let cached_bin = resource_path.join("dlssnr-amd/dlssnr.bin");
    if cached_bin.exists() {
        fs::copy(&cached_bin, &dest_path).map_err(|e| format!("Falha ao copiar bin final: {}", e))?;
        Ok(dest_path.to_string_lossy().to_string())
    } else {
        Err("A extração falhou: dlssnr.bin não foi gerado pelo backend.".to_string())
    }
}
