import { useI18n } from "../../i18n/I18nContext";

const english: Record<string, string> = {
  "Todo o prefixo será apagado permanentemente, incluindo jogos, programas, configurações e saves. Todos os jogos que usam esse prefixo serão removidos da biblioteca. Os atalhos também serão removidos da área de trabalho e das pastas de aplicativos. Outros arquivos fora do prefixo serão preservados. Deseja continuar?": "The entire prefix will be permanently deleted, including games, programs, settings and saves. All games using this prefix will be removed from the library. Shortcuts will also be removed from the desktop and application folders. Files outside the prefix will be kept. Continue?",
  "Instalar ou adicionar?": "Install or add?",
  "Instalar": "Install",
  "Adicionar": "Add",
  "Reparar": "Repair",
  "Duplicar": "Duplicate",
  "Desinstalar": "Uninstall",
  "Configurações": "Settings",
  "Já está na biblioteca": "Already in the library",
  "Consultando a biblioteca…": "Checking the library…",
  "Registro na biblioteca": "Library entry",
  "Qual prefixo deseja usar para reparar?": "Which prefix should be repaired?",
  "Onde deseja criar o prefixo?": "Where should the prefix be created?",
  "Onde deseja instalar?": "Where should it be installed?",
  "Selecionar instalador": "Select installer",
  "Selecionar executável": "Select executable",
  "Padrão": "Default",
  "Escolher": "Choose",
  "Local de instalação": "Installation location",
  "Alterar local de instalação": "Change installation location",
  "Executar com Proton": "Run with Proton",
  "Reparar com Proton": "Repair with Proton",
  "Instalar com Proton": "Install with Proton",
  "Versão do Proton": "Proton version",
  "Nome": "Name",
  "Digite o nome": "Enter a name",
  "Executável": "Executable",
  "Executável para reparar": "Executable to repair",
  "Verificando atalhos…": "Checking shortcuts…",
  "Não foi possível verificar os atalhos": "Could not check shortcuts",
  "Remover atalho da área de trabalho": "Remove desktop shortcut",
  "Criar atalho na área de trabalho": "Create desktop shortcut",
  "Atualizar atalho ao reparar ✓": "Update shortcut when repairing ✓",
  "Atualizar atalho": "Update shortcut",
  "Reparação em andamento": "Repair in progress",
  "Instalação em andamento": "Installation in progress",
  "Encerrando os processos…": "Stopping processes…",
  "Aguardando a atualização do prefixo…": "Waiting for the prefix update…",
  "Aguardando o instalador Windows finalizar…": "Waiting for the Windows installer to finish…",
  "A conclusão será liberada quando o Proton terminar de preparar o prefixo.": "You can finish when Proton has prepared the prefix.",
  "O Pelinstall permanece aberto enquanto o Proton prepara o prefixo e o instalador está em execução.": "Pelinstall stays open while Proton prepares the prefix and the installer is running.",
  "Prefixo desinstalado": "Prefix uninstalled",
  "Os registros que utilizavam esse prefixo foram removidos da biblioteca.": "Entries using this prefix were removed from the library.",
  "Adicionado à biblioteca": "Added to the library",
  "Reparação finalizada": "Repair complete",
  "Instalação finalizada": "Installation complete",
  "Qual executável deseja usar?": "Which executable should be used?",
  "Criar atalho": "Create shortcut",
  "Iniciar": "Start",
  "Atalho atualizado.": "Shortcut updated.",
  "Atalho removido.": "Shortcut removed.",
  "Atalhos removidos.": "Shortcuts removed.",
  "O executável será adicionado à biblioteca com o prefixo e o Proton selecionados.": "The executable will be added to the library with the selected prefix and Proton.",
  "O prefixo será atualizado se o Proton escolhido for diferente do atual.": "The prefix will be updated if the selected Proton differs from the current one.",
  "O instalador Windows abrirá suas próprias telas. Finalize a instalação nele para registrar os executáveis na biblioteca.": "The Windows installer will open its own windows. Finish installation there to register the executables in the library.",
  "Cancelando…": "Cancelling…",
  "Cancelar reparação": "Cancel repair",
  "Cancelar instalação": "Cancel installation",
  "Voltar": "Back",
  "Próximo": "Next",
  "Adicionando…": "Adding…",
  "Salvando…": "Saving…",
  "Concluir": "Finish",
  "Abrir PeliGames": "Open PeliGames",
  "Ícone do executável": "Executable icon",
  "Nenhum executável selecionado": "No executable selected",
  "Desinstalar?": "Uninstall?",
  "Cancelar reparação?": "Cancel repair?",
  "Cancelar instalação?": "Cancel installation?",
  "Encerrar instalação": "Stop installation",
  "Configuração incompleta": "Incomplete configuration",
  "Deseja sair e descartar a configuração iniciada?": "Exit and discard the current configuration?",
  "Deseja encerrar a atualização do prefixo? Os arquivos e logs serão preservados, mas a preparação pode ficar incompleta. As alterações do registro não serão salvas.": "Stop updating the prefix? Files and logs will be kept, but preparation may be incomplete. Library changes will not be saved.",
  "Deseja encerrar o instalador e os processos deste prefixo? A instalação pode ficar incompleta. O prefixo e os logs serão preservados e nenhum jogo será registrado por esta tentativa.": "Stop the installer and this prefix’s processes? Installation may be incomplete. The prefix and logs will be kept and no game will be registered for this attempt.",
  "Destino:": "Destination:",
  "Atalho criado:": "Shortcut created:",
  "executável(is) registrado(s) no PeliGames.": "executable(s) registered in PeliGames."
};

export function useInstallerText() {
  const { language } = useI18n();
  return (text: string) => language === "en" ? english[text] ?? text : text;
}
